CREATE TABLE `user` (
	`id` INT(5) NOT NULL AUTO_INCREMENT,
	`head` VARCHAR(300) NULL DEFAULT NULL,
	`name` VARCHAR(20) NOT NULL,
	`phone` VARCHAR(14) NULL DEFAULT NULL,
	`picture` VARCHAR(3000) NULL DEFAULT NULL,
	`sex` INT(11) NOT NULL,
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1